// Config model, loaded from the single editable config file.
//
// Unknown keys are ignored and missing keys fall back to documented defaults, so
// the file stays hand-editable and forward-compatible. Anything genuinely
// required — a camera needs an id, and credentials if the body wants them — is
// validated up front and reported as a list of problems rather than one at a
// time, because fixing config at 8am should take one pass.
#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace camd {

struct CameraConfig {
    std::string id;        // stable key used in the API path
    std::string label;     // human name for the UI
    std::string model;     // expected model; the camera's own report wins
    std::string ip;        // static address, informational — matching is by MAC
    std::string mac;       // optional: pins this config entry to one body
    std::string username;  // per-body, generated by the camera
    std::string password;
    std::string fingerprint;
};

struct ConnectionConfig {
    int heartbeatIntervalMs = 2000;
    int heartbeatTimeoutMs = 6000;
    std::vector<int> reconnectBackoffMs{1000, 2000, 4000, 8000, 15000};
    int reconnectBackoffMaxMs = 15000;
    // How long a REST request will wait for a camera worker before giving up and
    // returning 504. Bounded so one wedged camera cannot tie up the HTTP layer.
    int commandTimeoutMs = 3000;
    // Discovery re-scan interval while any configured camera is missing.
    int discoveryIntervalMs = 2000;
};

struct LoggingConfig {
    std::string dir = "./logs";
    std::string level = "info";
    std::uint64_t maxSizeBytes = 20ull * 1024 * 1024;
    int maxFiles = 30;
};

struct Config {
    std::string bind = "127.0.0.1";
    int restPort = 8787;
    std::string wsPath = "/ws";
    ConnectionConfig connection;
    LoggingConfig logging;
    std::vector<CameraConfig> cameras;

    // Returns true on success. On failure `errors` holds every problem found.
    static bool loadFile(const std::string& path, Config& out,
                         std::vector<std::string>& errors);
    static bool loadString(const std::string& text, Config& out,
                           std::vector<std::string>& errors);

    const CameraConfig* findById(const std::string& id) const;
};

}  // namespace camd
