#!/usr/bin/env bash
# Builds CamBridge.app — a double-clickable macOS launcher.
#
# The app is a thin wrapper: it starts camd and cambridge, waits for them, opens
# the browser, and stops both when you quit. All the real code stays in this repo,
# so the app never goes stale — it resolves the repo path at build time and runs
# whatever is checked out there.
#
# Usage:
#   ./scripts/make-app.sh                  builds ./CamBridge.app
#   ./scripts/make-app.sh /Applications    builds it there instead
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST_DIR="${1:-${REPO_ROOT}}"
APP="${DEST_DIR%/}/CamBridge.app"

rm -rf "${APP}"
mkdir -p "${APP}/Contents/MacOS" "${APP}/Contents/Resources"

cat > "${APP}/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>CamBridge</string>
    <key>CFBundleDisplayName</key><string>CamBridge</string>
    <key>CFBundleIdentifier</key><string>studio.cambridge.app</string>
    <key>CFBundleVersion</key><string>1.0</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleExecutable</key><string>CamBridge</string>
    <key>CFBundleIconFile</key><string>CamBridge</string>
    <key>NSHighResolutionCapable</key><true/>
    <!-- Stays in the Dock so there is an obvious way to quit, which also stops
         both background processes. -->
    <key>LSUIElement</key><false/>
    <key>LSMinimumSystemVersion</key><string>12.1</string>
</dict>
</plist>
PLIST

cat > "${APP}/Contents/MacOS/CamBridge" <<LAUNCHER
#!/bin/bash
# CamBridge launcher. Generated by scripts/make-app.sh — edit that, not this.
REPO="${REPO_ROOT}"
exec "\${REPO}/scripts/app-launch.sh"
LAUNCHER
chmod +x "${APP}/Contents/MacOS/CamBridge"

# A simple icon so it is recognisable in the Dock. Built from SVG when the tools
# are available; skipped harmlessly when they are not.
ICONSET="$(mktemp -d)/CamBridge.iconset"
mkdir -p "${ICONSET}"
cat > "${ICONSET}/icon.svg" <<'SVG'
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <rect width="1024" height="1024" rx="220" fill="#171b20"/>
  <rect x="196" y="250" width="270" height="90" rx="28" fill="#4da3ff"/>
  <circle cx="512" cy="590" r="230" fill="none" stroke="#4da3ff" stroke-width="70"/>
  <circle cx="512" cy="590" r="96" fill="#ef4d5a"/>
</svg>
SVG
if command -v qlmanage >/dev/null 2>&1 && command -v sips >/dev/null 2>&1 && command -v iconutil >/dev/null 2>&1; then
  if sips -s format png "${ICONSET}/icon.svg" --out "${ICONSET}/base.png" >/dev/null 2>&1; then
    for sz in 16 32 64 128 256 512; do
      sips -z "${sz}" "${sz}" "${ICONSET}/base.png" --out "${ICONSET}/icon_${sz}x${sz}.png" >/dev/null 2>&1 || true
      sips -z $((sz * 2)) $((sz * 2)) "${ICONSET}/base.png" --out "${ICONSET}/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1 || true
    done
    rm -f "${ICONSET}/icon.svg" "${ICONSET}/base.png"
    iconutil -c icns "${ICONSET}" -o "${APP}/Contents/Resources/CamBridge.icns" 2>/dev/null || true
  fi
fi
rm -rf "$(dirname "${ICONSET}")"

# A downloaded-then-generated bundle can pick up a quarantine flag; clear it so
# Gatekeeper does not block the first launch.
xattr -cr "${APP}" 2>/dev/null || true

cat <<EOF

Built ${APP}

Double-click it to start CamBridge. It will:
  - start camd and the cambridge web server
  - wait until the daemon is answering
  - open the control panel in your browser

Quitting the app (Cmd-Q, or right-click the Dock icon) stops both.

To keep it in the Dock permanently, drag it to /Applications first:
  ./scripts/make-app.sh /Applications
EOF
